"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { Github, Linkedin, Mail, Phone, Send, ShieldCheck, Terminal } from "lucide-react";
import SectionHeading from "./SectionHeading";
import ContactWorldMap from "./ContactWorldMap";
import { profile } from "@/lib/data";

export default function Contact(){
 const [form,setForm]=useState({name:"",email:"",subject:"",message:""});
 const change=(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 const submit=(e:React.FormEvent)=>{e.preventDefault();const subject=encodeURIComponent(form.subject||"Portfolio Contact");const body=encodeURIComponent(`${form.message}\n\n— ${form.name} (${form.email})`);window.location.href=`mailto:${profile.email}?subject=${subject}&body=${body}`};
 return <section id="contact" className="relative overflow-hidden"><div className="relative z-10 mx-auto max-w-5xl px-6 py-28"><SectionHeading eyebrow="// ENCRYPTED_CHANNEL" title="Contact" accent="volt"/>
 <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="secure-terminal relative overflow-hidden rounded-xl border border-neon/30 bg-[#050a09]/80 shadow-[0_0_45px_rgba(57,255,140,.08)] backdrop-blur-xl">
  <ContactWorldMap />
  <div className="relative z-10 flex items-center justify-between border-b border-neon/20 bg-neon/[.035] px-5 py-3"><div className="flex items-center gap-3"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-red-400/70"/><span className="h-2.5 w-2.5 rounded-full bg-yellow-300/70"/><span className="h-2.5 w-2.5 rounded-full bg-neon/80"/></div><span className="font-mono text-[10px] tracking-[.22em] text-white/45">SECURE_TERMINAL // CONTACT</span></div><ShieldCheck size={16} className="text-neon"/></div>
  <div className="relative z-10 grid lg:grid-cols-[.85fr_1.15fr]"><div className="border-b border-neon/15 bg-[#050a09]/55 p-6 backdrop-blur-sm lg:border-b-0 lg:border-r"><div className="font-mono text-xs leading-7"><p className="text-neon">$ establish_connection</p><p className="text-white/45">› channel: encrypted</p><p className="text-white/45">› status: <span className="text-neon">READY</span></p><p className="mt-4 text-white/70">Open to entry-level SOC Analyst and Security Analyst opportunities.</p></div><div className="mt-7 space-y-3"><a href={`mailto:${profile.email}`} className="terminal-contact-link"><Mail size={15}/><span><small>EMAIL</small>{profile.email}</span></a><a href={`tel:${profile.phone.replace(/\s/g,"")}`} className="terminal-contact-link"><Phone size={15}/><span><small>PHONE</small>{profile.phone}</span></a><a href={profile.github} target="_blank" rel="noreferrer" className="terminal-contact-link"><Github size={15}/><span><small>GITHUB</small>vasanth-void-0x</span></a><a href={profile.linkedin} target="_blank" rel="noreferrer" className="terminal-contact-link"><Linkedin size={15}/><span><small>LINKEDIN</small>vasanth-2k4</span></a></div></div>
  <form onSubmit={submit} className="space-y-4 bg-[#050a09]/45 p-6 backdrop-blur-sm"><div className="mb-2 flex items-center gap-2 font-mono text-[10px] tracking-[.25em] text-neon"><Terminal size={14}/> COMPOSE_MESSAGE</div><div className="grid gap-4 sm:grid-cols-2"><input name="name" required value={form.name} onChange={change} placeholder="> name" className="terminal-input"/><input name="email" type="email" required value={form.email} onChange={change} placeholder="> email" className="terminal-input"/></div><input name="subject" required value={form.subject} onChange={change} placeholder="> subject" className="terminal-input"/><textarea name="message" required rows={5} value={form.message} onChange={change} placeholder="> message..." className="terminal-input resize-none"/><button className="flex w-full items-center justify-center gap-2 rounded border border-neon/60 bg-neon/10 py-3 font-mono text-[11px] tracking-[.22em] text-neon shadow-neon-glow transition hover:bg-neon hover:text-void"><Send size={15}/> SEND VIA EMAIL</button></form></div>
 </motion.div></div></section>;
}
